### PR TITLE
Entrega Desafio - Alan

### PR DESCRIPTION
**Pull request by alan-rocha**

### CODE REVIEW

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Pull request closed without merging**
