### PR TITLE
Desafio Bravo

### PR DESCRIPTION
**Pull request by ed-vieira**
Enviando a conclusão do desafio Bravo para análise técnica

### CODE REVIEW

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Pull request closed without merging**
