### PR TITLE
Entrega do desafio challenge-bravo

### PR DESCRIPTION
**Pull request by olivic9**

### CODE REVIEW

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Pull request closed without merging**
